[window]
dynamic_title = true
opacity = 1.0

[shell]
program = "/bin/zsh"

[font]
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Bold" }
italic = { family = "Fira Code", style = "Italic" }
bold_italic = { family = "Fira Code", style = "Bold Italic" }
size = 8

[colors]
transparent_background_colors = true

[cursor]
thickness = 0.15
